const data = new Date();
console.log(data)
console.log(data.getDay())
console.log(data.getDate())
console.log(data.getMonth())
console.log(data.getYear())
console.log(data.getFullYear())
console.log(data.getTime())
console.log('timezone', data.getTimezoneOffset())
console.log(data.getHours())
console.log(data.getSeconds())
console.log(data.getMinutes())
console.log(data.getUTCHours())
